### ISSUE TITLE
Holiday schedule

### ISSUE THREAD

**Issue by mileserickson** [anstosa/ferry.fyi#12]
On the 4th of July, ferry.fyi showed a regular weekday schedule instead of the holiday schedule. The extra evening runs were not shown.

**Comment by anstosa** [comment]
Thanks for reporting! Believe it or not, WSDOT actually [publishes an API](https://www.wsdot.wa.gov/ferries/api/schedule/documentation/rest.html) for this which is my upstream data source for schedules. I'm using the `/scheduletoday` endpoint which I assumed reported holiday times but I guess I don't know that for sure. Unfortunately even their `/schedule` endpoint doesn't let you query the past so I can't double check but I will set a reminder for Labor Day to confirm that it's using the correct schedule
