### ISSUE TITLE
Late ferry (still at dock) shown as having departed early

### ISSUE THREAD

**Issue by mileserickson** [anstosa/ferry.fyi#16]
At 6:27 p.m., ferry.fyi was showing that the 6:10 departure from Mukilteo was predicted to be 28 minutes late, i.e. at 6:38. This is accurate. I'm on board at 6:33 and it's still loading vehicles.

But, it also says that the 6:10 ferry already departed 38 minutes ago at 5:49. That's clearly incorrect.

![F1D2FD83-2662-4E16-A3EA-3455266B13FF](https://user-images.githubusercontent.com/68300/61165272-1d693680-a4d3-11e9-8611-f72ed695a6ac.jpeg)

**Comment by anstosa** [comment]
Yup, good catch. Looks like math is wrong because I was categorizing "past" sailings as anything past the scheduled departure date, not past the estimated actual departure date.

**Comment by anstosa** [comment]
I believe I've fixed this (need to write some mocks and unit tests at some point...). Deploying now

**Comment by anstosa** [comment]
jk, still broken. `hasPassed` flag should be false still on this last one (11mins is correct but pointing the wrong direction because of the flag)
![Screenshot_20190722-172514](https://user-images.githubusercontent.com/568242/61673825-e8fd3380-aca5-11e9-9cc2-0f35df64cfc1.png)
