### ISSUE TITLE
Same vessel is an hour late and on time

### ISSUE THREAD

**Issue by mileserickson** [anstosa/ferry.fyi#28]
![1012FDBD-0469-4FE0-B02D-CBF9F1396F47](https://user-images.githubusercontent.com/68300/103967257-76407c00-5116-11eb-8b21-fda4c037d862.png)

At 2020-01-07 18:30 PST the M/V Suquamish was simultaneously reported to be an hour late for the 5:35 sailing from Clinton and also on time for the 6:35 sailing. This seems like a bug, though it could originate on the WSF side.

**Comment by anstosa** [comment]
Vessels now use shared state on the server so it's no longer possible for a vessel to report two different delay times. The latest fetched info now takes precedence. Data may still be wrong but at least it's not inconsistent
