### ISSUE TITLE
Directions reversed on "severe weather" schedule?

### ISSUE THREAD

**Issue by mileserickson** [anstosa/ferry.fyi#30]
It looks like today's "severe weather" schedule has the Clinton departure times listed under "Mukilteo-Clinton" and the Mukilteo departure times listed under "Clinton-Mukilteo" -- so strange!

<img width="736" alt="Screen Shot 2021-02-15 at 12 18 31 PM" src="https://user-images.githubusercontent.com/68300/107989964-42b00780-6f88-11eb-9910-085bb444e893.png">
<img width="736" alt="Screen Shot 2021-02-15 at 12 18 37 PM" src="https://user-images.githubusercontent.com/68300/107989968-43e13480-6f88-11eb-8e1d-8a7c2c94fbea.png">

**Comment by anstosa** [comment]
Hmm try incognito or a hard cache clear. I think there might be an issue with the original schedule being remembered somehow? It's showing up right for me:
683533
![image](https://user-images.githubusercontent.com/568242/107990355-2791c780-6f89-11eb-8012-85843d284497.png)

**Comment by mileserickson** [comment]
Looks fine on my end now when I bring it up (no reload required), but that certainly was strange!
